# Generated by Django 2.2.6 on 2019-11-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='queries/%Y/%m/%d/'),
        ),
    ]
